server:
  port: 8088
  
spring:  datasource:
    url: jdbc:mysql://139.196.183.233:3306/yanyang_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: HikariPool
    minimum-idle: 8
    maximum-pool-size: 100
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource
    # #初始化连接
    # initial-size: 10
    # #最大连接数量
    # max-active: 100
    # #最大空闲连接
    # max-idle: 8
    # #最小空闲连接
    # min-idle: 8
    # #检测数据库的查询语句
    # validation-query: SELECT 1 from dual
    # test-on-borrow: true
    # test-on-return: true
    # test-while-idle: true
    # #是否在自动回收超时连接的时候打印连接的超时错误
    # log-abandoned: true
    # #是否自动回收超时连接
    # remove-abandoned: true
    # #超时时间(以秒数为单位)
    # remove-abandoned-timeout: 180
    # #<!-- 超时等待时间以毫秒为单位 6000毫秒/1000等于60秒 -->
    # max-wait: 1000
    # #每隔五分钟检测空闲超过10分钟的连接
    # min-evictable-idle-time-millis: 600000
    # time-between-eviction-runs-millis: 300000

# mybatis 下划线自动转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true